name: Build Athar APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build APK from PWA
        uses: larsmarius/pwa-to-apk-action@v1
        with:
          # الرابط الجديد بتاعك
          url: "https://athar-silk.vercel.app/"
          # اسم التطبيق (خلينا نكتبه بالانجليزي هنا عشان الـ File System بس)
          name: "Athar"
          # صورة الايكون
          icon: "icon-512.png"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Athar-App
          path: ./*.apk
